# This would parse PDF file downloaded from
# <https://www.axa.com.sg/pdf/our_solutions/employee-health-benefits/group-clinicare-insurance/clinicare_panel_of_clinics.pdf>
#
# The excel file generated by <https://www.pdftoexcelonline.com/en/>
#
# The CSV file is converted by Numbers from Apple


=begin
creek.sheets.each do |s|
end
=end
